version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mediasite-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mediasite
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: mediasite-pgdata
